server:
  port: ${PORT:8089}

info:
  app:
    name: testcontainers
    description: '@application.description@'
    version: '@application.version@'
    group: '@application.group@'
    gitCurrentBranch: '@application.current.branch@'
    gitChangeSet: '@application.latest.revision@'
    buildDate: '@application.timestamp@'
    restApi: true
    usingDatabase: true

spring:
  datasource:
    dataSourceClassName: oracle.jdbc.pool.OracleDataSource
    url: jdbc:oracle:thin:@localhost:55012/xe
    username: zion_uploader
    password: zion_uploader
  jpa:
    database: ORACLE
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
        id:
          new_generator_mappings: true
        connection:
          handling_mode: DELAYED_ACQUISITION_AND_RELEASE_AFTER_TRANSACTION
      jadira:
        usertype:
          javaZone: UTC
          databaseZone: UTC
  liquibase:
    contexts: ${deployment.environment.name}
    change-log: classpath:db/changelog/db.changelog-master.yaml
